### ISSUE TITLE
Add Tests 

### ISSUE THREAD

**Issue by rhemon** [fossasia/searss#21]
We should be adding tests, and should try to have 100% coverage.

**Comment by In-vincible** [comment]
Hi @rhemon I would like to write tests, can you help me get started?

**Comment by rhemon** [comment]
@In-vincible  sorry for the late response, but yes go ahead. i would suggest you use unittest. and have a test for each function, since to have 100% coverage I think every conditional parts and outputs need to be tested. if you need further help, ask here, I will try to response quickly. I am new to unittesting so if we are stuck we will find the solution together 😉

**Comment by In-vincible** [comment]
Just read ur reply right now I am on a trip, I will be returning back day after tomorrow, please give me 2 day time for starting work if possible.

**Comment by jayanthchandra** [comment]
@In-vincible , currently it supports for two search engine with just two features, we can add more test for other engines. if you need any help, let us know.

**Comment by rhemon** [comment]
Its partially done by #25 and #28 and for improvement there is another issue, so closing this since it will only be a repetition.
