### ISSUE TITLE
DuckduckGo vs Google

### ISSUE THREAD

**Issue by nikhilkumarsingh** [fossasia/searss#6]
@mariobehling  suggested to keep an option for users to choose between the google and duckduckgo search engine.
My point is that 
- Working with google search requires the use of mechanize library which is not available for python 3.
  So, Python 3 users can't use this python script. (If version compatibility isn't an issue, I'm fine with it)
- Using only duckduckgo search removes this dependency. So, now the code is Python 2 & 3 compatible as well as a mechanize dependency is also removed.

Let me know your views over this @mariobehling

**Comment by mariobehling** [comment]
@nikhilkumarsingh Thanks. We need compatibility with Google. Once the library is available for Python3 we can move to Python 3

**Comment by nikhilkumarsingh** [comment]
Ok. So I will make a pull request with both options( google search and duckduckgo) available for rss feed generation.
The script is only for python 2 users for now.
Thanks @mariobehling

**Comment by nikhilkumarsingh** [comment]
I have made both options available (google and duckduckgo) in new pull request.
But I am unable to resolve conflicts. Any ideas?  @mariobehling

**Comment by nikhilkumarsingh** [comment]
I have also fixed a problem in google search scraper in PR #8 .
The current version is not giving an XML output.
Check it out @mariobehling

**Comment by mariobehling** [comment]
@nikhilkumarsingh Thank you. Yes, how can we get the XML output?

**Comment by nikhilkumarsingh** [comment]
@mariobehling That issue has been fixed with this commit to the PR #8 : https://github.com/fossasia/searss/pull/8/commits/c0bb47cfd9091efbd72c502834e209c9ed6dd108
